package bibliotecaria;

import bibliotecaria.emprestimo;
import javax.swing.JOptionPane;
import compartilhadas.pesquisar_livro;

public class View_bibliotecaria extends javax.swing.JFrame {

    public View_bibliotecaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_cadastro_livro = new javax.swing.JMenuItem();
        menu_pesquisa_livro = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_cadastro_aluno = new javax.swing.JMenuItem();
        menu_aluno_pesquisa = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu_emprestimo = new javax.swing.JMenuItem();
        menu_devolucao = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        principal.setMinimumSize(new java.awt.Dimension(0, 2));
        principal.setPreferredSize(new java.awt.Dimension(900, 640));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces_img/Moodle Biblioteca.png"))); // NOI18N

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, Short.MAX_VALUE)
        );
        principal.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(principal);
        principal.setBounds(0, 0, 1070, 570);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(null);
        jMenuBar1.setToolTipText("");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces_img/icons8_Bookmark_32px_1.png"))); // NOI18N
        jMenu1.setText("Livro");
        jMenu1.setPreferredSize(new java.awt.Dimension(100, 32));
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        menu_cadastro_livro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces_img/icons8_Add_32px.png"))); // NOI18N
        menu_cadastro_livro.setText("Cadastro");
        menu_cadastro_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadastro_livroActionPerformed(evt);
            }
        });
        jMenu1.add(menu_cadastro_livro);

        menu_pesquisa_livro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces_img/icons8_Search_32px.png"))); // NOI18N
        menu_pesquisa_livro.setText("Pesquisa");
        menu_pesquisa_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pesquisa_livroActionPerformed(evt);
            }
        });
        jMenu1.add(menu_pesquisa_livro);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 153, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces_img/icons8_Contacts_32px.png"))); // NOI18N
        jMenu2.setText("Aluno");
        jMenu2.setMaximumSize(new java.awt.Dimension(100, 32767));

        menu_cadastro_aluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces_img/icons8_Add_32px.png"))); // NOI18N
        menu_cadastro_aluno.setText("Cadastro");
        menu_cadastro_aluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_cadastro_alunoMouseClicked(evt);
            }
        });
        menu_cadastro_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadastro_alunoActionPerformed(evt);
            }
        });
        jMenu2.add(menu_cadastro_aluno);

        menu_aluno_pesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces_img/icons8_Search_32px.png"))); // NOI18N
        menu_aluno_pesquisa.setText("Pesquisa");
        menu_aluno_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_aluno_pesquisaActionPerformed(evt);
            }
        });
        jMenu2.add(menu_aluno_pesquisa);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(0, 102, 255));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces_img/icons8_Schedule_32px.png"))); // NOI18N
        jMenu3.setText("Processo");
        jMenu3.setPreferredSize(new java.awt.Dimension(100, 32));

        menu_emprestimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces_img/icons8_Event_32px.png"))); // NOI18N
        menu_emprestimo.setText("Emprestimo");
        menu_emprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_emprestimoActionPerformed(evt);
            }
        });
        jMenu3.add(menu_emprestimo);

        menu_devolucao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces_img/icons8_Today_32px.png"))); // NOI18N
        menu_devolucao.setText("Devolução");
        menu_devolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_devolucaoActionPerformed(evt);
            }
        });
        jMenu3.add(menu_devolucao);

        jMenuBar1.add(jMenu3);

<<<<<<< HEAD
        jMenu4.setText("Nome generico");
=======
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces_img/icons8_Services_26px.png"))); // NOI18N
        jMenu4.setText("Configurar");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
>>>>>>> mudanca-tetse
        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces_img/icons8_Exit_32px_1.png"))); // NOI18N
        jMenu5.setText("Deslogar");
        jMenu5.setMaximumSize(new java.awt.Dimension(100, 32767));
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1080, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_cadastro_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadastro_alunoActionPerformed
        Cadastro_Aluno cad_aluno = new Cadastro_Aluno();
        principal.add(cad_aluno);
        cad_aluno.setVisible(true);
    }//GEN-LAST:event_menu_cadastro_alunoActionPerformed

    private void menu_aluno_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_aluno_pesquisaActionPerformed
        pesquisar_aluno tela_pes_aluno = new pesquisar_aluno();
        principal.add(tela_pes_aluno);
        tela_pes_aluno.setVisible(true);
    }//GEN-LAST:event_menu_aluno_pesquisaActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void menu_pesquisa_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pesquisa_livroActionPerformed
       pesquisar_livro tela_pes_livro = new pesquisar_livro();
        principal.add(tela_pes_livro);
        tela_pes_livro.setVisible(true);
    }//GEN-LAST:event_menu_pesquisa_livroActionPerformed

    private void menu_emprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_emprestimoActionPerformed
        emprestimo tela_emprestimo = new emprestimo();
        principal.add(tela_emprestimo);
        tela_emprestimo.setVisible(true);
    }//GEN-LAST:event_menu_emprestimoActionPerformed

    private void menu_cadastro_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadastro_livroActionPerformed
<<<<<<< HEAD
        Cadastro_livro tela_cad_livro = new Cadastro_livro();
=======
        cadastrar_livro tela_cad_livro = new cadastrar_livro();
>>>>>>> mudanca-tetse
        principal.add(tela_cad_livro);
        tela_cad_livro.setVisible(true);
    }//GEN-LAST:event_menu_cadastro_livroActionPerformed

    private void menu_devolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_devolucaoActionPerformed
        Devolucao tela_devolucao = new Devolucao();
        principal.add(tela_devolucao);
        tela_devolucao.setVisible(true);
    }//GEN-LAST:event_menu_devolucaoActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void menu_cadastro_alunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_cadastro_alunoMouseClicked
        
    }//GEN-LAST:event_menu_cadastro_alunoMouseClicked

<<<<<<< HEAD
=======
    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
       configurar config = new configurar();
        principal.add(config);
        config.setVisible(true);
    }//GEN-LAST:event_jMenu4MouseClicked

>>>>>>> mudanca-tetse
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_bibliotecaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_bibliotecaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_bibliotecaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_bibliotecaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menu_aluno_pesquisa;
    private javax.swing.JMenuItem menu_cadastro_aluno;
    private javax.swing.JMenuItem menu_cadastro_livro;
    private javax.swing.JMenuItem menu_devolucao;
    private javax.swing.JMenuItem menu_emprestimo;
    private javax.swing.JMenuItem menu_pesquisa_livro;
    private javax.swing.JDesktopPane principal;
    // End of variables declaration//GEN-END:variables
}
